version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: homeserver-telegram-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    network_mode: host  # Используем host network для доступа к существующим сервисам
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s